name: Run Colab Notebook

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert nbformat jupyter pandas google-auth google-auth-oauthlib

      - name: Execute Colab Notebook
        run: |
          jupyter nbconvert --to notebook --execute _1_24112024_get_data_previous_game_day_and_parse_to_statistics.ipynb \
            --output executed_notebook.ipynb

      - name: Upload executed notebook as artifact
        uses: actions/upload-artifact@v3
        with:
          name: executed-notebook
          path: executed_notebook.ipynb
