name: Run Colab Notebook

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Run the workflow daily at midnight (UTC)
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert nbformat jupyter pandas google-auth google-auth-oauthlib

      # Run the notebook
      - name: Execute Colab Notebook
        run: |
          jupyter nbconvert --to notebook --execute _1_24112024_get_data_previous_game_day_and_parse_to_statistics.ipynb \
            --output executed_notebook.ipynb

      # Save the executed notebook
      - name: Upload executed notebook as artifact
        uses: actions/upload-artifact@v3
        with:
          name: executed-notebook
          path: executed_notebook.ipynb
